# Generated by Django 2.2.3 on 2019-08-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190818_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='context_html',
            field=models.TextField(blank=True, editable=False, verbose_name='正文html代码'),
        ),
    ]
