# Generated by Django 2.2.3 on 2019-08-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_context_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='context_html',
            new_name='content_html',
        ),
    ]
